trigger:
- main

jobs:
  - job: Build
    pool:
      name: Oracle VM
    steps:
      - task: NodeTool@0
        inputs:
          versionSource: "spec"
          versionSpec: ">=6.15.0"
        displayName: "Install Node.js"
      - script: |
          echo "do some linting"
        displayName: "linting"
      - script: |
          echo "do some unit test"
        displayName: "unit test"
      - script: |
          node -v
          echo $(pwd)
          echo $(ls)
          cd counters-backend/
          echo $(pwd)
          echo $(ls)
          npm install
          npm run build
        displayName: "npm install and build"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true
        displayName: "Archive files"
      - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        artifact: drop
        displayName: "Upload artifact"
