trigger:
- none

resources:
  pipelines:
  - pipeline: Counters
    source: Build-Pipeline
    trigger:
      branches:
      - main

jobs:
- deployment: Deploy
  displayName: Deploy
  environment: Counters Environment
  pool: 
    name: Oracle VM
  strategy:
    runOnce:
      deploy:
        steps:          
        - download: Counters
          artifact: drop
          displayName: "Download artifact"
        - task: ExtractFiles@1
          inputs:
            archiveFilePatterns: "$(PIPELINE.WORKSPACE)/Counters/drop/$(resources.pipeline.Counters.runID).zip"
            destinationFolder: "$(agent.builddirectory)/live"
            cleanDestinationFolder: true
            overwriteExistingFiles: true
          displayName: "Extract files"
        - bash: |
            echo "PIPELINE.WORKSPACE: $(PIPELINE.WORKSPACE)"
            echo "agent.builddirectory: $(agent.builddirectory)"
            echo "Starting App in $NODE_ENV mode on PORT $PORT_PROD"
            cd $(agent.builddirectory)/live
            pm2 startOrReload pm2.json
            pm2 save
          env:
            NODE_ENV: $(NODE_ENV)
            PORT_PROD: $(PORT_PROD)
            REDIS_URL_PROD: $(REDIS_URL_PROD)
            MONGO_URL_PROD: $(MONGO_URL_PROD)
          displayName: "pm2 startOrReload"